Feature/BRPA-759-get-options-middleware
vtex-apps/tiktok-tbp pull request #11
Opened 2022-01-10 12:27 UTC by MIzidio

#### What is the purpose of this pull request?

Moving the getOptions middleware from tiktok-tbp-config to this repository and adding the countries names to countryList return

#### How to test it?

[Workspace](http://tiktok--izidio.myvtex.com/_v/api/tiktok-tbp/options)

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/l0HU53cSTpf2bvEzK/giphy.gif)

#### Types of changes

- [ ] Chore (non-breaking change which doesn't change any functionalities)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2022-01-10 21:07 UTC, ConradoClark requested changes

2022-01-10 21:07 UTC, ConradoClark commented on node/index.ts
> +  },
Hmm 🤔 this function is already being exposed through `GraphQL` in the other PR. I don't think we're going to use this route in the front-end.

2022-01-10 21:07 UTC, ConradoClark commented on node/middlewares/getOptions.ts
> +import type { GetTikTokDataResponse } from '../typings/getTikTokDataResponse'
Same here. This is already being done by the `externalDataService`.

2022-01-11 12:23 UTC, MIzidio commented on node/middlewares/getOptions.ts
> +import type { GetTikTokDataResponse } from '../typings/getTikTokDataResponse'
So can I delete this file ?

2022-01-11 13:59 UTC, felipefadul commented
Unfortunately, I think all of this PR was done in [this PR](https://github.com/vtex-apps/tiktok-tbp/pull/10).
Issues [BRPA-755](https://vtex-dev.atlassian.net/browse/BRPA-755) and [BRPA-759](https://vtex-dev.atlassian.net/browse/BRPA-759) were very similar. Aren't they both done in the [PR-10](https://github.com/vtex-apps/tiktok-tbp/pull/10) and [PR-14](https://github.com/vtex-apps/tiktok-tbp/pull/14)?

2022-01-11 14:14 UTC, ConradoClark commented
> Unfortunately, I think all of this PR was done in [this PR](https://github.com/vtex-apps/tiktok-tbp/pull/10).
> Issues [BRPA-755](https://vtex-dev.atlassian.net/browse/BRPA-755) and [BRPA-759](https://vtex-dev.atlassian.net/browse/BRPA-759) were very similar. Aren't they both done in the [PR-10](https://github.com/vtex-apps/tiktok-tbp/pull/10) and [PR-14](https://github.com/vtex-apps/tiktok-tbp/pull/14)?


Yes, I believe so. I ended up doing BRPA-759 with the migration, @MIzidio can change it to done.

2022-01-11 14:16 UTC, ConradoClark commented on node/middlewares/getOptions.ts
> +import type { GetTikTokDataResponse } from '../typings/getTikTokDataResponse'
As Fadul mentioned below, I think it's safe to close this PR altogether.

2022-01-11 15:01 UTC, closed without merging