Feature/brpa 1209 register affiliate
vtex-apps/tiktok-tbp pull request #67
Opened 2022-04-04 14:48 UTC by MIzidio

#### What is the purpose of this pull request?

- Create an affiliate when connecting.

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/XO8RMtRaK73isIt0i2/giphy.gif)

#### Types of changes

- [ ] Chore (non-breaking change which doesn't change any functionalities)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2022-04-04 14:52 UTC, gabrielHosino approved these changes

2022-04-04 17:31 UTC, anamaiabap approved these changes

2022-04-04 18:47 UTC, felipefadul requested changes
Good job, Izidio! I have a suggestion for improvement for the method [saveBusinessProfileData](https://github.com/vtex-apps/tiktok-tbp/blob/937ae2fed1113a8734417d3e7382fbb1ae13c8ec/node/services/businessProfileService.ts#L51). It's actually doing so much more logic now than save business profile data, rsrs. I think it would be a good practice if the affiliate and catalog logic would be extracted to another separated methods. You could manage the order of calling each method on the resolver. But you can have a method for registerAccount, other for getFullSync, other for registerAffiliate and leave the saveBusinessProfileData method only for save the data on app settings as it is supposed to be. This way the code will be more decoupled and I think it will be better logged on Splunk and facilitate in case of debug. What do you think?

2022-04-04 18:47 UTC, felipefadul commented on node/resolvers/submitStartupForm.ts
> +  await appSettings.saveValueToAppSettings(
```suggestion
  await appSettings.saveValueOnAppSettings('storeName', storeName)
  await appSettings.saveValueOnAppSettings('email', email)
  await appSettings.saveValueOnAppSettings('affiliateId', affiliateId)
  await appSettings.saveValueOnAppSettings(
```

Build is failing because of this. I refactored the name of this method in the last PR.

2022-04-04 18:47 UTC, felipefadul commented on node/services/businessProfileService.ts
> +        name: 'TIK TOK',
```suggestion
        name: 'TIKTOK',
```

2022-04-04 18:47 UTC, felipefadul commented on node/services/businessProfileService.ts
> +      const searchEndpoint = ` https://tiktok-catalog-webapi-stable.vtex.systems/integration/${data.account}/update-sku`
```suggestion
      const searchEndpoint = `https://tiktok-catalog-webapi-stable.vtex.systems/integration/${data.account}/update-sku`
```

2022-04-05 13:15 UTC, pscruzzz reviewed
LGTM

2022-04-05 13:16 UTC, pscruzzz approved these changes

2022-04-05 23:42 UTC, felipefadul approved these changes
Really really good refactoring, @MIzidio ! 💯 
I only left some suggestions on how I would do it, but it's up to you, just details. You've already done a great job!

2022-04-05 23:42 UTC, felipefadul commented on node/services/affiliateService.ts
> +      const appSettings = await service.getAppSettings()
```suggestion
      const { affiliateId, email } = await service.getAppSettings()
```

2022-04-05 23:42 UTC, felipefadul commented on node/services/catalogIntegrationService.ts
> +    businessProfileData: BusinessData
Here you only need `catalogId` and `bcId` from this `businessProfileData` object. For the purpose of an account registration method, I would add `catalogId` and `bcId`as params instead of the whole object, even if the number of params grows. But it's up to you.

2022-04-06 14:49 UTC, MIzidio commented on node/services/affiliateService.ts
> +      const appSettings = await service.getAppSettings()
Done!

2022-04-06 14:49 UTC, merged